[package]
name = "playground-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
playground-api = "0.2"
poise = "0.6.1"
regex = "1.11.1"
tokio = { version = "1.45.0", features = ["full"] }
